import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import ts from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

export default [
  // 忽略文件
  {
    ignores: [
      'node_modules/',
      'dist/',
      'build/',
      '*.log',
      'pnpm-lock.yaml',
      'package-lock.json',
      'yarn.lock',
      '.svelte-kit/',
      '.svelte-kit/**/*',
      '*.json',
      '*.yaml',
      '*.yml',
      '*.toml',
      '*.html',
    ],
  },

  // JavaScript/TypeScript 配置
  js.configs.recommended,
  {
    files: [
      '**/*.js',
      '**/*.mjs',
      '**/*.cjs',
      '**/*.ts',
      '**/*.mts',
      '**/*.tsx',
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        browser: true,
        node: true,
        module: true,
        console: false,
        log: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        Worker: true,
        URL: true,
        URLSearchParams: true,
        MessageEvent: true,
        AbortController: true,
        AbortSignal: true,
        fetch: true,
        Headers: true,
        Request: true,
        RequestInit: true,
        Response: true,
        localStorage: true,
        sessionStorage: true,
        window: true,
        document: true,
        navigator: true,
        location: true,
        history: true,
        performance: true,
        NodeJS: true,
        IntersectionObserver: true,
        IntersectionObserverInit: true,
        ResizeObserver: true,
        CustomEvent: true,
        MouseEvent: true,
        KeyboardEvent: true,
        HTMLElement: true,
        Element: true,
        HTMLCanvasElement: true,
        HTMLImageElement: true,
        HTMLParagraphElement: true,
        HTMLHeadingElement: true,
        HTMLVideoElement: true,
        CanvasRenderingContext2D: true,
        Blob: true,
        FileList: true,
        Image: true,
        self: true,
        any: true,
        btoa: true,
        atob: true,
      },
    },
    plugins: {
      '@typescript-eslint': ts,
    },
    rules: {
      // 基本规则
      'no-console': 'warn',
      'no-debugger': 'warn',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_' },
      ],
      'no-undef': 'error',
      'no-empty': 'error',
      'no-extra-semi': 'error',
      semi: ['error', 'always'],
      quotes: ['error', 'single'],
      indent: ['error', 2],
      'linebreak-style': ['error', 'unix'],
      'eol-last': ['error', 'always'],
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'comma-spacing': ['error', { before: false, after: true }],
      'space-infix-ops': 'error',
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'always'],
      'arrow-spacing': ['error', { before: true, after: true }],
      'no-trailing-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
    },
  },

  // Svelte 配置
  ...svelte.configs['flat/recommended'],
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parserOptions: {
        parser: tsParser,
      },
      globals: {
        browser: true,
        node: true,
        module: true,
        console: false,
        log: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        Worker: true,
        URL: true,
        URLSearchParams: true,
        MessageEvent: true,
        AbortController: true,
        AbortSignal: true,
        fetch: true,
        Headers: true,
        Request: true,
        RequestInit: true,
        Response: true,
        localStorage: true,
        sessionStorage: true,
        window: true,
        document: true,
        navigator: true,
        location: true,
        history: true,
        performance: true,
        NodeJS: true,
        IntersectionObserver: true,
        IntersectionObserverInit: true,
        ResizeObserver: true,
        CustomEvent: true,
        MouseEvent: true,
        KeyboardEvent: true,
        HTMLElement: true,
        Element: true,
        HTMLCanvasElement: true,
        HTMLImageElement: true,
        HTMLParagraphElement: true,
        HTMLHeadingElement: true,
        HTMLVideoElement: true,
        CanvasRenderingContext2D: true,
        Blob: true,
        FileList: true,
        HTMLInputElement: true,
        HTMLSelectElement: true,
        HTMLButtonElement: true,
        HTMLDivElement: true,
        HTMLSpanElement: true,
        HTMLAnchorElement: true,
        HTMLFormElement: true,
        HTMLTextAreaElement: true,
        Event: true,
        Image: true,
        self: true,
        any: true,
        btoa: true,
        atob: true,
        withDefaults: true,
        defineProps: true,
        defineEmits: true,
        defineExpose: true,
        $: true,
        $$: true,
      },
    },
    plugins: {
      '@typescript-eslint': ts,
    },
    rules: {
      // 基本规则
      'no-console': 'warn',
      'no-debugger': 'warn',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_' },
      ],
      'no-undef': 'error',
      'no-empty': 'error',
      'no-extra-semi': 'error',
      semi: ['error', 'always'],
      quotes: ['error', 'single'],
      indent: ['error', 2],
      'linebreak-style': ['error', 'unix'],
      'eol-last': ['error', 'always'],
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'comma-spacing': ['error', { before: false, after: true }],
      'space-infix-ops': 'error',
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'always'],
      'arrow-spacing': ['error', { before: true, after: true }],
      'no-trailing-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      // 禁用 XSS 警告，因为使用了 sanitizeHtml 函数
      'svelte/no-at-html-tags': 'off',
    },
  },
];
